/**:
    ros__parameters:
        # Generic parameters
        use_sim_time: false
        namespace: ""
        nodeName: ""                    # rv2_sensors only
        id: ""                          # rv2_sensors only

        devManageService: "devmanage_0" # Service name
        devInterface: ""                # rv2_sensors only
        procStatusRegPeriod_ms: 0.0     # Procedure status registration period

        qosService: "qos_0"             # Service name
        qosDirPath: ""                  # rv2_sensors only

        safetyService: ""               # Service name

        timesyncService: ""             # Service name
        timesyncPeriod_ms: 0.0          # rv2_sensors only
        timesyncAccuracy_ms: 0.0        # rv2_sensors only
        timesyncWaitService: false      # rv2_sensors only

        # DevManageServer parameters
        devManageServiceNodeName: "rv2_devmanageserver"
        devManageServiceNodeID: "0"
        devManageServerDirPath: "devmanageserver/nodes"
        procExpTimeout_ms: 1000.0
        nodeAddrStoreStrategy: 0

        # QoSServer parameters
        qosServiceNodeName: "rv2_qosserver"
        qosServiceNodeID: "0"
        qosServerDirPath: "qosserver"
